data:
  test_size: 0.2
  random_state: 42

training:
  epochs: 1000
  batch_size: 64
  validation_split: 0.2
  fine_tuning_epochs: 50

model:
  layers: [512, 256, 128, 64, 32]
  activation: relu
  optimizer: rmsprop
  loss: huber
  metrics: [mae]

output:
  model_dir: saved_models/
  logs_dir: logs/
  predictions_dir: predictions/
  report_file: predictions/report.html

callbacks:
  early_stopping:
    monitor: val_loss
    patience: 15
    restore_best_weights: true
  reduce_lr:
    monitor: val_loss
    factor: 0.5
    patience: 10